[package]
name = "actix_app"
version = "0.1.0"
authors = ["Gavin Gong <kefengong@gmail.com>"]

[dependencies]
actix-web = "3.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.3.16"